### ISSUE TITLE
Panic in SLG solver: clear_strands_after_cycle invoked on strand in table without a selected subgoal

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/chalk#571]
The following test case (extracted from `liballoc`) causes the SGL solve to panic (the recursive solver handles this just fine)

```rust
#[test]
fn to_owned_rc_impl() {
    test! {
        program {
            #[non_enumerable]
            #[lang(sized)]
            trait Sized { }
            trait From<T> where T: Sized {
            }
            trait ToOwned {
                type Owned;
            }

            impl<T> ToOwned for [T] where T: Sized {
                type Owned = Vec<T>;
            }

            struct Rc<T> { }

            struct Vec<T> where T: Sized {}
            struct Cow<'x, T> where T: ToOwned {}

            impl<'a, T> From<&'a [T]> for Rc<[T]> where T: Sized {}
            impl<T> From<Vec<T>> for Rc<[T]> where T: Sized {}
            impl<'a, B> From<Cow<'a, B>> for Rc<B>
            where
                B: ToOwned,
                Rc<B>: From<&'a B>,
                Rc<B>: From<<B as ToOwned>::Owned>
            {
            }
        }

        goal {
            exists<S, T> {
                Rc<S>: From<T>
            }
        } yields {
            "Ambiguous; no inference guidance"
        }
    }
}
```

<details>

<summary>Output and backtrace</summary>

```text
running 1 test
program {
    # [non_enumerable] # [lang(sized)] trait Sized { } trait From < T > where
    T : Sized { } trait ToOwned { type Owned ; } impl < T > ToOwned for [T]
    where T : Sized { type Owned = Vec < T > ; } struct Rc < T > { } struct
    Vec < T > where T : Sized { } struct Cow < 'x, T > where T : ToOwned { }
    impl < 'a, T > From < & 'a [T] > for Rc < [T] > where T : Sized { } impl <
    T > From < Vec < T >> for Rc < [T] > where T : Sized { } impl < 'a, B
    > From < Cow < 'a, B >> for Rc < B > where B : ToOwned, Rc < B > : From <
    & 'a B >, Rc < B > : From << B as ToOwned > :: Owned > { }
}
----------------------------------------------------------------------
goal { exists < S, T > { Rc < S > : From < T > } }
using solver: SLG { max_size: 10, expected_answers: None }
thread 'test::existential_types::to_owned_rc_impl' panicked at 'clear_strands_after_cycle invoked on strand in table without a selected subgoal: Canonical { value: ExClause { subst: [?0 := {slice}<^0.0>], ambiguous: true, constraints: [], subgoals: [], delayed_subgoals: [], answer_time: TimeStamp { clock: 0 }, floundered_subgoals: [FlounderedSubgoal { floundered_literal: Positive(InEnvironment { environment: Env([]), goal: ForAll<> { Implemented(^1.0: Sized) } }), floundered_time: TimeStamp { clock: 0 } }, FlounderedSubgoal { floundered_literal: Positive(InEnvironment { environment: Env([]), goal: AliasEq(<{slice}<^0.0> as ToOwned>::Owned = Vec<^0.0>) }), floundered_time: TimeStamp { clock: 0 } }] }, binders: [U0 with kind type] }', /home/matthew/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:373
  13: chalk_engine::logic::SolveState<I,C,CO>::clear_strands_after_cycle::{{closure}}
             at /home/matthew/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16
  14: core::option::Option<T>::unwrap_or_else
             at /home/matthew/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/option.rs:428
  15: chalk_engine::logic::SolveState<I,C,CO>::clear_strands_after_cycle
             at ./chalk-engine/src/logic.rs:1257
  16: chalk_engine::logic::SolveState<I,C,CO>::clear_strands_after_cycle
             at ./chalk-engine/src/logic.rs:1267
  17: chalk_engine::logic::SolveState<I,C,CO>::on_no_strands_left
             at ./chalk-engine/src/logic.rs:1175
  18: chalk_engine::logic::SolveState<I,C,CO>::ensure_root_answer
             at ./chalk-engine/src/logic.rs:528
  19: chalk_engine::logic::<impl chalk_engine::forest::Forest<I,C>>::root_answer
             at ./chalk-engine/src/logic.rs:93
  20: <chalk_engine::forest::ForestSolver<I,C,CO> as chalk_engine::context::AnswerStream<I>>::peek_answer
             at ./chalk-engine/src/forest.rs:74
  21: <chalk_engine::forest::ForestSolver<I,C,CO> as chalk_engine::context::AnswerStream<I>>::next_answer
             at ./chalk-engine/src/forest.rs:113
  22: <chalk_engine::slg::SlgContextOps<I> as chalk_engine::slg::aggregate::AggregateOps<I>>::make_solution
             at ./chalk-engine/src/slg/aggregate.rs:34
  23: <chalk_engine::solve::SLGSolver<I> as chalk_solve::solve::Solver<I>>::solve
             at ./chalk-engine/src/solve.rs:40
  24: <chalk_integration::SolverImpl as chalk_solve::solve::Solver<chalk_integration::interner::ChalkIr>>::solve
             at chalk-integration/src/lib.rs:102
  25: chalk_integration::db::ChalkDatabase::solve
             at chalk-integration/src/db.rs:60
  26: lib::test::solve_goal::{{closure}}::{{closure}}
             at tests/test/mod.rs:258
  27: chalk_integration::tls::set_current_program::{{closure}}
             at ./chalk-integration/src/tls.rs:160
  28: std::thread::local::LocalKey<T>::try_with
             at /home/matthew/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  29: std::thread::local::LocalKey<T>::with
             at /home/matthew/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  30: chalk_integration::tls::set_current_program
             at ./chalk-integration/src/tls.rs:158
  31: lib::test::solve_goal::{{closure}}
             at tests/test/mod.rs:244
  32: tracing_core::dispatcher::with_default
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.10/src/dispatcher.rs:222
  33: tracing::subscriber::with_default
             at /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.15/src/subscriber.rs:24
  34: chalk_solve::logging::with_tracing_logs
             at ./chalk-solve/src/logging.rs:11
  35: lib::test::solve_goal
             at tests/test/mod.rs:219
  36: lib::test::existential_types::to_owned_rc_impl
             at tests/test/existential_types.rs:446
  37: lib::test::existential_types::to_owned_rc_impl::{{closure}}
             at tests/test/existential_types.rs:445
  38: core::ops::function::FnOnce::call_once
             at /home/matthew/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  39: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/liballoc/boxed.rs:1008
  40: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:318
  41: std::panicking::try::do_call
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:331
  42: std::panicking::try
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panicking.rs:274
  43: std::panic::catch_unwind
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/panic.rs:394
  44: test::run_test_in_process
             at src/libtest/lib.rs:541
  45: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
test test::existential_types::to_owned_rc_impl ... FAILED

failures:

failures:
    test::existential_types::to_owned_rc_impl

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 375 filtered out

error: test failed, to rerun pass '-p chalk --test lib'
The terminal process "/usr/bin/fish '-c', 'cargo test --package chalk --test lib -- test::existential_types::to_owned_rc_impl --exact --nocapture'" terminated with exit code: 101.
```

</details>

**Comment by jackh726** [comment]
A slightly more minimized version:
```
#[test]
fn to_owned_rc_impl() {
    test! {
        program {
            #[non_enumerable]
            #[lang(sized)]
            trait Sized { }
            trait From<T> {}
            trait ToOwned {
                type Owned;
            }

            impl<T> ToOwned for [T] where T: Sized {
                type Owned = Vec<T>;
            }

            struct Rc<T> { }

            struct Vec<T> {}
            struct Cow<'x, T> {}

            impl<T> From<Vec<T>> for Rc<[T]> {}
            impl<'a, B> From<Cow<'a, B>> for Rc<B>
            where
                B: ToOwned,
                Rc<B>: From<&'a B>,
                Rc<B>: From<<B as ToOwned>::Owned>
            {
            }
        }

        goal {
            exists<S, T> {
                Rc<S>: From<T>
            }
        } yields[SolverChoice::slg_default()] {
            "Ambiguous; no inference guidance"
        }
    }
}
```

Interestingly, if you remove `non_enumerable` for `Sized`, you actually get the result `Unique; for<?U0> { substitution [?0 := {slice}<^0.0>, ?1 := Vec<^0.0>], lifetime constraints [] }`. This is actually wrong, since `?0 := B, ?1 := Cow<'a, B>` is also a valid substitution.

**Comment by matthewjasper** [comment]
Enumerable sized doesn't work correctly (`exists<T> { T: Sized }` is considered too have no solutions, rather that lots. I'll raise an issue for it.

**Comment by jackh726** [comment]
We should have an issue somewhere (I can't find it), but this is a known issue that for builtin types. We can't enumerate them for builtin traits.

**Comment by jackh726** [comment]
Okay, been looking a little bit more into this today. A very similar case that *doesn't* have a problem:
```
#[test]
fn to_owned_rc_impl() {
    test! {
        program {
            struct X {}
            struct Y {}
            struct Z {}

            trait From<T> {}
            trait ToOwned {
                type Owned;
            }

            impl ToOwned for X {
                type Owned = Y;
            }

            struct Rc<T> { }

            struct Cow {}

            impl From<Y> for Rc<X> {}
            impl<B> From<Z> for Rc<B>
            where
                B: ToOwned,
                Rc<B>: From<<B as ToOwned>::Owned>
            {
            }
        }

        goal {
            exists<S, T> {
                Rc<S>: From<T>
            }
        } yields[SolverChoice::slg_default()] {
            "Ambiguous; definite substitution for<?U0> { [?0 := X, ?1 := ^0.0] }"
        }
    }
}
```
This correctly gives an ambiguous solution, because both `Rc<X>: Y` and `Rc<X>: Z` apply.

Still looking into this more.

**Comment by jackh726** [comment]
So, I *think* it comes down to `resolvent_clause{goal=Implemented(Rc<?0>: From<<?0 as ToOwned>::Owned>), clause=for<type> Implemented(Rc<^0.0>: From<Cow<^0.0>>) :- ForAll<> { Implemented(^1.0: ToOwned) }, ForAll<> { Implemented(Rc<^1.0>: From<<^1.0 as ToOwned>::Owned>) }}`. Specifically, that last bit will end up in a cycle. I still haven't figured out exactly why this cycle is having a problem.

**Comment by nathanwhit** [comment]
Another instance of this panic is on [this branch](https://github.com/nathanwhit/chalk/tree/sem-syn), when performing WF checks for the following program

```
program {
    trait Iterator {
        type Item;
    }
    #[non_enumerable]
    trait IntoIterator {
        type Item;
        type IntoIter: Iterator<Item = <Self as IntoIterator>::Item>;
    }
    struct Flatten<I> {}

    impl<I, U> Iterator for Flatten<I>
    where
        I: Iterator,
        <I as Iterator>::Item: IntoIterator<IntoIter = U>,
        <I as Iterator>::Item: IntoIterator<Item = <U as Iterator>::Item>,
        U: Iterator
    {
        type Item = <U as Iterator>::Item;
    }
}
```

with the WF goal:
<details>

```
all(
    ForAll<type, type> { 
        if ([
                for<> FromEnv(^1.0: Iterator),
                for<> AliasEq(<<^1.0 as Iterator>::Item as IntoIterator>::IntoIter = ^1.1), 
                for<> FromEnv(<^1.0 as Iterator>::Item: IntoIterator), 
                for<> AliasEq(<<^1.0 as Iterator>::Item as IntoIterator>::Item = <^1.1 as Iterator>::Item), 
                for<> FromEnv(<^1.0 as Iterator>::Item: IntoIterator), 
                for<> FromEnv(^1.1: Iterator), 
                for<> FromEnv(Flatten<^1.0>)
            ])
        { 
            all(
                WellFormed(<<^0.0 as Iterator>::Item as IntoIterator>::IntoIter), 
                WellFormed(<^0.0 as Iterator>::Item), 
                WellFormed(<^0.0 as Iterator>::Item), 
                WellFormed(<<^0.0 as Iterator>::Item as IntoIterator>::Item), 
                WellFormed(<^0.0 as Iterator>::Item), WellFormed(<^0.0 as Iterator>::Item), 
                WellFormed(Flatten<^0.0>: Iterator)
            ) 
        } 
    }, 
    ForAll<type, type> { 
        if ([
            for<> FromEnv(^1.0: Iterator), 
            for<> AliasEq(<<^1.0 as Iterator>::Item as IntoIterator>::IntoIter = ^1.1), 
            for<> FromEnv(<^1.0 as Iterator>::Item: IntoIterator), 
            for<> AliasEq(<<^1.0 as Iterator>::Item as IntoIterator>::Item = <^1.1 as Iterator>::Item), 
            for<> FromEnv(<^1.0 as Iterator>::Item: IntoIterator), 
            for<> FromEnv(^1.1: Iterator), 
            for<> FromEnv(Flatten<^1.0>)
            ]) 
        { 
            if ([]) { 
                WellFormed(<^0.1 as Iterator>::Item) 
            } 
        } 
    }
)
```
</details>

And here's the panic message/backtrace:
<details>
```
thread 'test::projection::iterator_flatten' panicked at 'clear_strands_after_cycle invoked on strand in table without a selected subgoal: Canonical { value: ExClause { subst: [?0 := ^0.0, ?1 := ^0.1], ambiguous: true, constraints: [], subgoals: [], delayed_subgoals: [], answer_time: TimeStamp { clock: 0 }, floundered_subgoals: [FlounderedSubgoal { floundered_literal: Positive(InEnvironment { environment: Env([for<> FromEnv(!1_0: Iterator), for<type> AliasEq(<^0.0 as IntoIterator>::IntoIter = !1_1) :- AliasEq(<!1_0 as Iterator>::Item = ^0.0), for<type> FromEnv(^0.0: IntoIterator) :- AliasEq(<!1_0 as Iterator>::Item = ^0.0), for<type, type> AliasEq(<^0.0 as IntoIterator>::Item = ^0.1) :- AliasEq(<!1_0 as Iterator>::Item = ^0.0), AliasEq(<!1_1 as Iterator>::Item = ^0.1), for<type> FromEnv(^0.0: IntoIterator) :- AliasEq(<!1_0 as Iterator>::Item = ^0.0), for<> FromEnv(!1_1: Iterator), for<> FromEnv(Flatten<!1_0>)]), goal: Normalize(<^0.0 as IntoIterator>::Item -> ^0.1) }), floundered_time: TimeStamp { clock: 0 } }] }, binders: [U1 with kind type, U1 with kind type] }', /Users/nathanw/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:214
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  12: rust_begin_unwind
             at src/libstd/panicking.rs:437
  13: std::panicking::begin_panic_fmt
             at src/libcore/../stdarch/crates/core_arch/src/macros.rs:403
  14: chalk_engine::logic::SolveState<I,C,CO>::clear_strands_after_cycle::{{closure}}
             at /Users/nathanw/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/macros.rs:16
  15: core::option::Option<T>::unwrap_or_else
             at /Users/nathanw/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/option.rs:425
  16: chalk_engine::logic::SolveState<I,C,CO>::clear_strands_after_cycle
             at ./chalk-engine/src/logic.rs:1256
  17: chalk_engine::logic::SolveState<I,C,CO>::clear_strands_after_cycle
             at ./chalk-engine/src/logic.rs:1266
  18: chalk_engine::logic::SolveState<I,C,CO>::on_no_strands_left
             at ./chalk-engine/src/logic.rs:1174
  19: chalk_engine::logic::SolveState<I,C,CO>::ensure_root_answer
             at ./chalk-engine/src/logic.rs:527
  20: chalk_engine::logic::<impl chalk_engine::forest::Forest<I,C>>::root_answer
             at ./chalk-engine/src/logic.rs:93
  21: <chalk_engine::forest::ForestSolver<I,C,CO> as chalk_engine::context::AnswerStream<I>>::peek_answer
             at ./chalk-engine/src/forest.rs:74
  22: <chalk_engine::forest::ForestSolver<I,C,CO> as chalk_engine::context::AnswerStream<I>>::next_answer
             at ./chalk-engine/src/forest.rs:113
  23: <chalk_engine::slg::SlgContextOps<I> as chalk_engine::slg::aggregate::AggregateOps<I>>::make_solution
             at ./chalk-engine/src/slg/aggregate.rs:34
  24: <chalk_engine::solve::SLGSolver<I> as chalk_solve::solve::Solver<I>>::solve
             at ./chalk-engine/src/solve.rs:40
  25: <chalk_integration::SolverImpl as chalk_solve::solve::Solver<chalk_integration::interner::ChalkIr>>::solve
             at chalk-integration/src/lib.rs:102
  26: chalk_solve::wf::WfSolver<I,S,SC>::verify_trait_impl
             at ./chalk-solve/src/wf.rs:257
  27: chalk_integration::query::checked_program::{{closure}}
             at chalk-integration/src/query.rs:155
  28: chalk_integration::tls::set_current_program::{{closure}}
             at chalk-integration/src/tls.rs:160
  29: std::thread::local::LocalKey<T>::try_with
             at /Users/nathanw/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  30: std::thread::local::LocalKey<T>::with
             at /Users/nathanw/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  31: chalk_integration::tls::set_current_program
             at chalk-integration/src/tls.rs:158
  32: chalk_integration::query::checked_program
             at chalk-integration/src/query.rs:147
  33: <chalk_integration::query::CheckedProgramQuery as salsa::plumbing::QueryFunction<DB>>::execute
             at chalk-integration/src/query.rs:46
  34: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade::{{closure}}
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.4/src/derived/slot.rs:217
  35: salsa::runtime::Runtime<DB>::execute_query_implementation
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.4/src/runtime.rs:352
  36: salsa::derived::slot::Slot<DB,Q,MP>::read_upgrade
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.4/src/derived/slot.rs:214
  37: salsa::derived::slot::Slot<DB,Q,MP>::read
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.4/src/derived/slot.rs:146
  38: <salsa::derived::DerivedStorage<DB,Q,MP> as salsa::plumbing::QueryStorageOps<DB,Q>>::try_fetch
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.4/src/derived.rs:140
  39: salsa::QueryTable<DB,Q>::try_get
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.4/src/lib.rs:484
  40: salsa::QueryTable<DB,Q>::get
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.14.4/src/lib.rs:480
  41: <T as chalk_integration::query::LoweringDatabase>::checked_program
             at chalk-integration/src/query.rs:27
  42: lib::test::solve_goal::{{closure}}
             at tests/test/mod.rs:229
  43: tracing_core::dispatcher::with_default
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-core-0.1.11/src/dispatcher.rs:237
  44: tracing::subscriber::with_default
             at /Users/nathanw/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.16/src/subscriber.rs:24
  45: chalk_solve::logging::with_tracing_logs
             at ./chalk-solve/src/logging.rs:11
  46: lib::test::solve_goal
             at tests/test/mod.rs:219
  47: lib::test::projection::iterator_flatten
             at tests/test/projection.rs:337
  48: lib::test::projection::iterator_flatten::{{closure}}
             at tests/test/projection.rs:335
  49: core::ops::function::FnOnce::call_once
             at /Users/nathanw/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/ops/function.rs:233
  50: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/liballoc/boxed.rs:1081
  51: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:318
  52: std::panicking::try::do_call
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:348
  53: std::panicking::try
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panicking.rs:325
  54: std::panic::catch_unwind
             at /rustc/346aec9b02f3c74f3fce97fd6bda24709d220e49/src/libstd/panic.rs:394
  55: test::run_test_in_process
             at src/libtest/lib.rs:541
  56: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
```
</details>

**Comment by nathanwhit** [comment]
Here's an ever so slightly more minimized version of the original test case, with some comments pointing out some of the necessary elements (i.e. if you change/remove one of them, the panic doesn't occur). Hope it's at least of some use

```
#[test]
fn panic_repro() {
    test! {
        program {
            // Some trait
            trait A { }

            // Trait with type param
            trait TyParamTrait<T> {
            }

            // Trait with assoc ty
            trait AssocTyTrait {
                type Ty;
            }


            // implementor must take type arg bounded by a trait
            impl<T> AssocTyTrait for ArgTaker<T> where T: A {
                // Doesn't matter
                type Ty = ();
            }

            struct Rc<T> { }

            struct ArgTaker<T> { }

            struct Other { }

            // param taken by trait must match the param of the impl below.
            impl<T> TyParamTrait<Other> for Rc<ArgTaker<T>> {}
            //                                 ^^^^^^^^^^^ must impl `AssocTyTrait`
            impl<B> TyParamTrait<Other> for Rc<B>
            where
                // for WF
                B: AssocTyTrait,
                // the type being projected must be the type param (`B`)
                Rc<B>: TyParamTrait<<B as AssocTyTrait>::Ty>
            {
            }
        }

        goal {
            // doesn't matter, error occurs in WF checking
            Other : A
        } yields {
            "No possible solution"
        }
    }
}
```
